language: node_js

node_js:
  - '10'
  - '11'

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn ci

jobs:
  include:
    - stage: deploy
      script:
        # publish on tag
        - if [ -n "$TRAVIS_TAG" ]; then node node_modules/.bin/workspace-publish; fi
        # note: the NPM_TOKEN needs to be set as an environment variable in the Travis settings
